// Profanity filter for co-parenting chat
// Uses substring matching so combinations like "dirty pussy" are caught

const BLOCKED_WORDS = [
  // Sexual / explicit
  "fuck", "fucker", "fucked", "fucking", "fucks", "motherfucker", "motherfucking",
  "shit", "shitty", "bullshit", "horseshit", "dipshit",
  "ass", "asshole", "arsehole", "jackass", "dumbass", "badass", "smartass",
  "bitch", "bitches", "bitching",
  "cock", "cocks", "cocksucker",
  "dick", "dicks",
  "pussy", "pussies",
  "cunt", "cunts",
  "tits", "titty", "titties",
  "boobs", "boob",
  "penis", "vagina", "vulva",
  "whore", "whores",
  "slut", "sluts",
  "ho ", "hoe", "hoes",
  "skank", "skanky",
  "wank", "wanker", "wankers", "wanking",
  "jizz", "cum ", "cumming", "cumshot",
  "blowjob", "blow job", "handjob", "hand job",
  "anal", "anus",
  "porn", "porno", "pornography",
  "rape", "rapist", "raping",
  "molest", "molester",
  "pedophile", "paedophile",
  "sex ", "sexy", "sexting",
  "nude", "nudes", "naked",
  "masturbat",
  "erection", "boner",
  "dildo", "vibrator",
  "stripper",
  "prostitut",

  // Insults / harassment
  "bastard", "bastards",
  "prick", "pricks",
  "twat", "twats",
  "tosser", "tossers",
  "bellend", "bell end",
  "knob", "knobhead",
  "wanker",
  "nonce",
  "scumbag", "scumbags",
  "deadbeat",
  "scum",
  "trash",
  "pig", "pigs",
  "slag", "slags",
  "retard", "retarded",
  "idiot", "idiots",
  "moron", "morons",
  "imbecile",
  "loser", "losers",
  "pathetic",
  "useless",
  "worthless",
  "piece of shit",
  "piece of crap",
  "stupid bitch",
  "dumb bitch",
  "ugly bitch",
  "fat bitch",
  "crazy bitch",

  // Body shaming
  "you are fat",
  "you're fat",
  "ur fat",
  "you are ugly",
  "you're ugly",
  "ur ugly",
  "you are gross",
  "you're gross",
  "you are disgusting",
  "you're disgusting",
  "so fat",
  "so ugly",
  "so gross",
  "fat pig",
  "fat cow",
  "fat slob",
  "fat lazy",
  "lazy fat",
  "obese",
  "you are obese",
  "you're obese",
  "lard",
  "fatso",
  "fatty",
  "tubby",
  "chubby",
  "porky",
  "you look disgusting",
  "you look horrible",
  "you look awful",
  "you look ugly",
  "you look fat",
  "look at yourself",
  "look in the mirror",
  "no one wants you",
  "nobody wants you",
  "no one loves you",
  "nobody loves you",
  "ugly inside",
  "ugly outside",
  "ugly person",
  "hideous",

  // Personal attacks / demeaning language
  "waste of space",
  "waste of time",
  "good for nothing",
  "good-for-nothing",
  "you are dumb",
  "you're dumb",
  "ur dumb",
  "are you dumb",
  "are you stupid",
  "are you blind",
  "are you deaf",
  "are you an idiot",
  "dumb dumb",
  "dummy",
  "so dumb",
  "so stupid",
  "so useless",
  "so pathetic",
  "so worthless",
  "you are stupid",
  "you're stupid",
  "ur stupid",
  "you are useless",
  "you're useless",
  "ur useless",
  "you are worthless",
  "you're worthless",
  "ur worthless",
  "you are pathetic",
  "you're pathetic",
  "you are a joke",
  "you're a joke",
  "what a joke",
  "absolute joke",
  "complete joke",
  "terrible parent",
  "bad parent",
  "bad mother",
  "bad father",
  "bad mum",
  "bad dad",
  "unfit parent",
  "unfit mother",
  "unfit father",
  "you are crazy",
  "you're crazy",
  "ur crazy",
  "you are insane",
  "you're insane",
  "you are mental",
  "you're mental",
  "psycho",
  "lunatic",
  "freak",
  "weirdo",
  "disgusting",
  "repulsive",
  "revolting",
  "horrible person",
  "awful person",
  "terrible person",
  "vile",
  "despicable",

  // Threats / hate
  "i hate you",
  "hate you",
  "kill yourself",
  "kill you",
  "go die",
  "drop dead",
  "i wish you were dead",
  "you should die",
  "i will hurt",
  "i'll hurt",
  "gonna hurt",
  "going to hurt",
  "threaten",

  // British
  "bollocks",
  "bugger",
  "bloody hell",
  "sod off",
  "git",
  "plonker",
  "muppet",
  "pillock",
  "numpty",
  "tosspot",

  // Drug references in abusive context
  "junkie",
  "crackhead",
  "druggie",

  // Sexual insults / slut-shaming directed at a person
  "bend over for",
  "bends over for",
  "bent over for",
  "legs open",
  "legs spread",
  "on her knees",
  "on his knees",
  "she just wants",
  "she only wants",
  "all she wants",
  "loves sucking",
  "love sucking",
  "loves giving",
  "loves taking",
  "sleeps around",
  "sleeping around",
  "slept around",
  "sleep around",
  "opening her legs",
  "opens her legs",
  "spreading her legs",
  "spreads her legs",
  "giving it up",
  "gives it up",
  "easy lay",
  "easy girl",
  "easy woman",
  "easy man",
  "town bicycle",
  "village bicycle",
  "everyone's had",
  "everyone has had",
  "been with everyone",
  "slept with everyone",
  "she'll sleep",
  "she will sleep",
  "he'll sleep",
  "he will sleep",
  "sleep with anyone",
  "slept with anyone",
  "wants any man",
  "wants any woman",
  "any guy she can",
  "any girl she can",
  "just wants sex",
  "only wants sex",
  "just wants a man",
  "just wants a woman",

  // Racial / discriminatory (common slurs)
  "nigger", "nigga",
  "chink", "chinky",
  "spic", "spick",
  "kike",
  "faggot", "fag ",
  "dyke",
  "tranny",
  "wetback",
  "cracker ",
  "redneck",

  // Misc abusive
  "goddamn", "god damn",
  "damn you",
  "go to hell",
  "selfish",
  "narcissist",
  "abuser",
  "neglect",
];

// Normalise leet-speak substitutions so "a$$" or "f*ck" are caught
function normalise(text) {
  return text
    .toLowerCase()
    .replace(/4/g, 'a')
    .replace(/@/g, 'a')
    .replace(/3/g, 'e')
    .replace(/1/g, 'i')
    .replace(/!/g, 'i')
    .replace(/0/g, 'o')
    .replace(/5/g, 's')
    .replace(/\$/g, 's')
    .replace(/\*/g, '')   // remove asterisks used to censor (f*ck → fck still caught by partial)
    .replace(/\./g, '')   // remove dots used to evade (f.u.c.k → fuck)
    .replace(/-/g, '');   // remove dashes (f-u-c-k → fuck)
}

export function containsProfanity(text) {
  const normalised = normalise(text);
  for (const word of BLOCKED_WORDS) {
    if (normalised.includes(word.toLowerCase())) return true;
  }
  return false;
}

export function getBlockedWord(text) {
  const normalised = normalise(text);
  for (const word of BLOCKED_WORDS) {
    if (normalised.includes(word.toLowerCase())) return word.trim();
  }
  return null;
}
